name: Django CI

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: comandos de sucesso
        run: ls/
      